### ISSUE TITLE
Need support for other Variants

### ISSUE THREAD

**Issue by RickKimball** [stm32duino/Arduino_Core_STM32F1#1]
It would be nice to have support for other variants. I think the BluePill would be a good one to try at first.

**Comment by rogerclarkmelbourne** [comment]
Still in progress ;-)

**Comment by rogerclarkmelbourne** [comment]
Some progress has been made, we now have a Blue Pill and Nucleo F103RB
and to some extents a Value Line STM Discovery F100 (but the static lib won't compile for this at the moment due to inclusion of USB files in the makefile - I suspect a separate makefile (.mk) is required for this variant

**Comment by rogerclarkmelbourne** [comment]
STM32 VL Discovery should now be working
Maple mini has now been added (though only the new bootloader version works - not sure why this is, and dont have time to debug this at the moment)
