### ISSUE TITLE
Compilation error with Wire library

### ISSUE THREAD

**Issue by ghost** [stm32duino/Arduino_Core_STM32F1#18]
Following the merge of the branch of danieleff, the Wire library doesn't compile. The header twi.h is not found.
Only tested with the Nucleo variant.

**Comment by rogerclarkmelbourne** [comment]
Fixed. (Thanks)
See https://github.com/stm32duino/Arduino_Core_STM32F1/commit/f0486c68214338a2a01816e131731f19d93cd8fe
