### ISSUE TITLE
Use pin enum names in g_APinDescription in BluePill variant.cpp

### ISSUE THREAD

**Issue by danieleff** [stm32duino/Arduino_Core_STM32F1#21]
The BluePill board does not have pin numbers written on the board, use pin names in its variant.cpp:
`extern const PinDescription g_APinDescription[]=`
`{`
`{ PA0, GPIO_PIN_0, GPIOA, ...`
`{ PA1, GPIO_PIN_1, GPIOA, ...`
`{ PA2, GPIO_PIN_2, GPIOA, ...`
`...`

**Comment by rogerclarkmelbourne** [comment]
Is this just for clarity in the code.

I already use pin names in my BluePill test code  e.g.

`pinMode(PB12,OUTPUT);`

and it works fine.

I have posted a separate issue about the complex way that pin name to Port / Pin is done (using a for loop), which seems a waste of time and code when I think it can be accomplished just using an array lookup

**Comment by rogerclarkmelbourne** [comment]
Edit.

I see what you mean

It still uses ARDUINO_PIN_A0 etc. I thought this had been changed to 0

I'll fix this
