### ISSUE TITLE
linker omits math lib

### ISSUE THREAD

**Issue by ProjectsByJRP** [stm32duino/Arduino_Core_STM32F1#22]
math lib is omitted when linking on the F1 core but not the F4 core. 

commenting out the line in platform.txt and replacing it with this one, from the F4 core seems to fix it:
`recipe.c.combine.pattern="{compiler.path}{compiler.c.elf.cmd}" -mcpu={build.mcu} -mthumb {compiler.c.elf.flags} "-T{build.variant.path}/{build.ldscript}" "-Wl,-Map,{build.path}/{build.project_name}.map" {compiler.c.elf.extra_flags} -o "{build.path}/{build.project_name}.elf" "-L{build.path}" -Wl,--start-group "{build.path}/core/syscalls_stm32.c.o" {object_files} "{build.variant.path}/{build.variant_system_lib}" "{build.path}/{archive_file}" -Wl,--end-group -lm -gcc --specs=nano.specs`

**Comment by rogerclarkmelbourne** [comment]
Thanks

Looks like adding -lm is probably the best solution
