### ISSUE TITLE
define NB_ANALOG_CHANNELS 15 in analog.h is not correct for all F1 devices

### ISSUE THREAD

**Issue by rogerclarkmelbourne** [stm32duino/Arduino_Core_STM32F1#25]
https://github.com/stm32duino/Arduino_Core_STM32F1/blob/master/cores/arduino/libstm32f1/analog.h#L71

is not correct for F103C as its only got 10 channels

This probably needs ifdef's around it to set the value based on MCU series and version.

However 
https://github.com/stm32duino/Arduino_Core_STM32F1/blob/master/cores/arduino/libstm32f1/analog.c#L105 would also need to be changed as it defines all 16 

I think the optimal solution may be to use if defined(...) in analog.c, so that only the applicable ADC channels for a specific MCU device are included in the array

**Comment by fpistm** [comment]
Fixed in https://github.com/stm32duino/Arduino_Core_STM32
