### ISSUE TITLE
analogWrite should work on more pins on some variants

### ISSUE THREAD

**Issue by rogerclarkmelbourne** [stm32duino/Arduino_Core_STM32F1#26]
Steps to reproduce

Install original version from boards manager package
Load example sketch Analog->Fading
change ledPin from 9 to 13
Upload

On Nucleo F103RB this seems to just flash the LED and not fade it, I checked with a logic analyser and it does not appear to deliver PWM on that pin

I tired on a different board on a different pin and got the same result

**Comment by rogerclarkmelbourne** [comment]
Edit

Looks like perhaps this is "by design"

PWM other pins just gives high or low

However I don't know why PWM is available for most pins ?

Tested pin 11 on the Nucleo again and it does do PWM.

This is more of an issue for the VL Discovery and all non-Nucleo boards where people will expect PWM on all pins that can support it.

**Comment by danieleff** [comment]
I think that is because those pins support hardware PWM. The other pins would need to use software interrupt. How is analogwrite done in libmaple?

**Comment by rogerclarkmelbourne** [comment]
I'm Not sure how libmaple does it.

**Comment by rogerclarkmelbourne** [comment]
Fading on the Black Pill LED PB12 does not work, but I thought it worked on the Blue Pill Led on PC13, but my Blue Pill now had a broken USB connection on the PCB :-(

So I'll need to connect STLink to test

**Comment by danieleff** [comment]
The following pins are currently set to (hardware) PWM: PA7, PB3, PB4, PB6, PB10, PC7
Here is a [list of possible PWM pins](https://gist.github.com/danieleff/fb7987d7e0dae6dbbbfb58beb87b1096), TIM (PWM) column.

**Comment by rogerclarkmelbourne** [comment]
Thanks

**Comment by danieleff** [comment]
There is one more thing that related to this: In `analogRead` and `analogWrite` there is a line: `uint32_t apin = ulPin&0x0000000F;`

It is only there because the size of g_anInputPinConfigured is only MAX_ANALOG_IOS. I guess it was copy-pasted accidentally to `analogWrite`.

Both of these lines should be removed, change size of g_anInputPinConfigured to MAX_DIGITAL_IOS, and take care of the increased ram size it in #27

**Comment by fpistm** [comment]
Fixed in https://github.com/stm32duino/Arduino_Core_STM32
