### ISSUE TITLE
Number of USB endpoints may be reduced

### ISSUE THREAD

**Issue by rogerclarkmelbourne** [stm32duino/Arduino_Core_STM32F1#31]
@stevstrong noticed that the number of USB end points is quite high (16) and can probably be reduce if we are just using the serial driver

https://github.com/stm32duino/Arduino_Core_STM32F1/tree/master/system/Drivers/STM32F1xx_HAL_Driver/Inc/stm32f1xx_hal_pcd.h#L121

However at the moment I'm trying to limit the number of changes to the HAL files, because if we want to update to a newer version of the HAL in the future any changes to those files would need to be re-applied

**Comment by fpistm** [comment]
Avoid make change in HAL.
