### ISSUE TITLE
HAL callback functions in the core should should be declared as weak so they can be overridden in the sketch

### ISSUE THREAD

**Issue by rogerclarkmelbourne** [stm32duino/Arduino_Core_STM32F1#33]
HAL callback functions in the core should should be declared as weak so they can be overridden in the sketch

**Comment by ghost** [comment]
Can you declare the same function weak more than one time?
In the doubt I tried and I can say that it is not possible because gcc returns an error (multiple definition).

**Comment by fpistm** [comment]
Close this issue as no update and already several weak function provided in https://github.com/stm32duino/Arduino_Core_STM32.
New issue could be opened in https://github.com/stm32duino/Arduino_Core_STM32/issues if specific one are requested.
