### ISSUE TITLE
Serial3 not found ?

### ISSUE THREAD

**Issue by hazmi-e205** [stm32duino/Arduino_Core_STM32F1#44]
I have a BluePhill board STM32F103C8t6. 
I can't use UART3 when i tried to use this Core.
![deepinscreenshot20170523110150](https://cloud.githubusercontent.com/assets/12555465/26338108/2159ca70-3f6d-11e7-83b2-33ef4467f430.png)

Actually, on STM32CubeMX i found the USART3. Check this..
![deepinscreenshot20170523110215](https://cloud.githubusercontent.com/assets/12555465/26338140/54594284-3f6d-11e7-82f1-67690bb1e76d.png)

**Comment by ghost** [comment]
@hazmi-e205 could you try the patch #45 . Let me know if there is any problem.

**Comment by hazmi-e205** [comment]
Sorry @fprwi6labs , I'm newbie...
On my Arduino Board Manager not available update file.

but I tried copy manually in directory: /home/hazmiarifin/.arduino15/packages/STM32/hardware/stm32f1/2017.1.20

And Still....
![deepinscreenshot20170523152230](https://cloud.githubusercontent.com/assets/12555465/26344978/f726dcf6-3f90-11e7-8b95-fd6dca8595e3.png)

**Comment by ghost** [comment]
Sorry  @hazmi-e205 I didn't generate new package for the Board Manager yet.

Just to be sure, did you replace uart.c & uart.h in cores/arduino/libstm32f1 and variant.cpp & variant.h in variants/STM32F103C_BluePill with the patched files?

Please checks that you find the Serial3 definition in .arduino15/packages/STM32/hardware/stm32f1/2017.1.20/variants/STM32F103C_BluePill/variant.cpp & variant.h.

**Comment by hazmi-e205** [comment]
Oke, it's compiled well. 
![deepinscreenshot20170523161727](https://cloud.githubusercontent.com/assets/12555465/26347308/ac41f8f8-3f98-11e7-8922-796f66876180.png)


I hope work fine too on my board.
I will try directly tomorrow.

Thank you for your help @fprwi6labs

**Comment by ghost** [comment]
Fine! 
Please let me know if Serial3 is completely functional.
Enjoy it!

**Comment by hazmi-e205** [comment]
On my board, I used multiserial example for checking received  data. But the result is...
![deepinscreenshot20170529085914](https://cloud.githubusercontent.com/assets/12555465/26565887/99e1a190-44de-11e7-8d8b-53e3fd20b434.png)

if i used "Generic STM32F103C" from @rogerclarkmelbourne repository. Work fine...
![deepinscreenshot20170529084722](https://cloud.githubusercontent.com/assets/12555465/26565960/07263716-44df-11e7-876e-1d9fe37028bc.png)

**Comment by ghost** [comment]
@hazmi-e205 
It seems to be an mounting problem with the serial port.
Could you give us more information (flashing method, OS, ...)?

**Comment by hazmi-e205** [comment]
@fprwi6labs 
I'm using STLink for flashing my board.
my OS is deepin 15.4 (Debian Based)

I think you right, but I tried to check "lsusb" my board not listed
![deepinscreenshot20170530213051](https://cloud.githubusercontent.com/assets/12555465/26588356/a1aa37b4-4544-11e7-8c4c-c6d5a1aed1a8.png)

If the problem is mounting the serial port on my PC,  i tried simple program serial usb that work fine
![deepinscreenshot20170530213707](https://cloud.githubusercontent.com/assets/12555465/26588696/8de42888-4545-11e7-93d7-bc84556355f3.png)

**Comment by fpistm** [comment]
No update. 
Patch from @fprwi6labs  merged.
Anyway, this core is deprecated instead use https://github.com/stm32duino/Arduino_Core_STM32
