### ISSUE TITLE
I2C Tx slave mode limitation

### ISSUE THREAD

**Issue by ghost** [stm32duino/Arduino_Core_STM32F1#47]
Issue related to the following post: [http://stm32duino.com/viewtopic.php?f=48&t=2127](http://stm32duino.com/viewtopic.php?f=48&t=2127)
Linked with #46

**Comment by fpistm** [comment]
Hi,
As this repo will be merged to [https://github.com/stm32duino/Arduino_Core_STM32](https://github.com/stm32duino/Arduino_Core_STM32) and Serial has been reworked, this will be corrected to this one.
Moreover HAL for F1 has been updated. So we will check, if restriction has been removed.
