### ISSUE TITLE
UART begin() with two parameters is missing (Parity, Stop bits...)

### ISSUE THREAD

**Issue by Adminius** [stm32duino/Arduino_Core_STM32F1#48]
Hello,

in my project i need SERIAL_8E1 setting , but there is no begin function with two parameters available:
`Serial1.begin(19200, SERIAL_8E1)`
This settings are internaly availible:
https://github.com/stm32duino/Arduino_Core_STM32F1/blob/master/cores/arduino/libstm32f1/uart.c#L327

Can you please add it in Arduino style?

**Comment by ghost** [comment]
Hi @Adminius 

This feature will be available soon for F1.
We are working to merge STM32F1 with the generic repository [https://github.com/stm32duino/Arduino_Core_STM32](url).

**Comment by Adminius** [comment]
obsolete due to merge to generic repository
