### ISSUE TITLE
Board reboot without pressing a reset button.

### ISSUE THREAD

**Issue by Adminius** [stm32duino/Arduino_Core_STM32F1#49]
Hi,

i founded this solution:
http://www.stm32duino.com/viewtopic.php?t=678
`nvic_sys_reset();`
but this function is not included. 
Do i have another possibility to reset my board within software?

**Comment by rogerclarkmelbourne** [comment]
I'm not sure what the HAL way to do this is

That function is actually this code, which uses direct access to registers

```
void nvic_sys_reset() {
    uint32 prigroup = SCB_BASE->AIRCR & SCB_AIRCR_PRIGROUP;
    SCB_BASE->AIRCR = SCB_AIRCR_VECTKEY | SCB_AIRCR_SYSRESETREQ | prigroup;
    asm volatile("dsb");
    while (1)
        ;
}
```

**Comment by fpistm** [comment]
Hi @Adminius,
Just call:
NVIC_SystemReset();
it is not link to HAL. It is a CMSIS interface. It is available in core_cm3.h.

**Comment by bilbolodz** [comment]
Maybe you should use watchdog functionality?

**Comment by Adminius** [comment]
Maybe... :)
But how? ;)

**Comment by bilbolodz** [comment]
Not checked just google it: http://www.stm32duino.com/viewtopic.php?t=140

**Comment by rogerclarkmelbourne** [comment]
@bilbolodz 

Most of the stuff on the forum relates to the LibMaple core, not this new HAL based core.

Re: Using the WDT to reset..

Well I suppose you could do it that way, but if NVIC_SystemReset() exists in the CMSIS, I don't see any reason not to use it

**Comment by Adminius** [comment]
tested with L476RG. NVIC_SystemReset(); works. 
still waiting for BluePill :(
solved for me.
