### ISSUE TITLE
PWM resolution and other pin related settings

### ISSUE THREAD

**Issue by Adminius** [stm32duino/Arduino_Core_STM32F1#51]
Hi,
i'm confused about 8bit PWM resolution...
https://github.com/stm32duino/Arduino_Core_STM32F1/blob/master/variants/STM32F103C_BluePill/variant.h#L143
Is there a reason for it? or can i make a PR to increase it to 16bit?
Why is PWM supported only on few pins? (PA7,PB3,PB4,PB6,PB10)?
PWM can be used on at least 12 pins...

https://github.com/stm32duino/Arduino_Core_STM32F1/blob/master/variants/STM32F103C_BluePill/variant.cpp#L39
There are only A0-A3 available. But PA2,PA3,PA5,PA6,PA7,PB1 can also be used for ADC.

![grafik](https://user-images.githubusercontent.com/17052262/27282634-1f40b71e-54f1-11e7-906c-2b824536545e.png)

Similar issue: https://github.com/stm32duino/Arduino_Core_STM32F1/issues/26

**Comment by ghost** [comment]
Hi @Adminius 

Yes you can increase the PR to 16bits but I not sure about the final result. It depends on the final timer resolution.

The STM32F1 repository will be merged soon inside https://github.com/stm32duino/Arduino_Core_STM32. It will be easier to configure all pins of a board.

I invite you to start to look at the generic repository to see the new pin management.

**Comment by Adminius** [comment]
Timer 1-4 are 16bit timer. With 72Mhz CPU Clock and 16bit resolution it's abour 1.1khz PWM frequency.
i've made similar PR for SAMD21 core:
https://github.com/arduino/ArduinoCore-samd/pull/226/commits/a5e0003a7b85a7cf0dd614f55c7b3a8c1bbcec6d#diff-63b7293bbdf8f8f0f8b98336a5e85d83L215

the same way i would made it for STM32:

- Standard resolution 16bit

- All other resolution will be mapped to 16bit with mapResolution.


But I can wait until both cores will be merged...

**Comment by ghost** [comment]
There is a limitation for the moment. The resolution is limited to 8bits.
We will fix this problem as quick as possible.

**Comment by Adminius** [comment]
I think, it should be enouth to change this lines 
https://github.com/stm32duino/Arduino_Core_STM32F1/blob/master/variants/STM32F103C_BluePill/variant.h#L143
to:
#define PWM_RESOLUTION                16

#define PWM_FREQUENCY                 1000

#define PWM_MAX_DUTY_CYCLE            65535

**Comment by ghost** [comment]
@Adminius 

Did you test with this modification? Did you obtain the result you wanted?

Just for information: the STM32F1 merged inside the generic repository should be available next week.

**Comment by Adminius** [comment]
not tested yet. still waiting for my test board :(

next week sounds good 👍

**Comment by Adminius** [comment]
just tested this:
#define PWM_RESOLUTION 16
#define PWM_FREQUENCY 1000
#define PWM_MAX_DUTY_CYCLE 65535

on L476RG with 80Mhz
PWM frequency is 1.2 kHz (with 72MHz it will be 1.1 kHz)

user can use analogWriteResolution(res) to change the resolution.

**Comment by ghost** [comment]
Thank you @Adminius 
I forgot to use the function analogWriteResolution while I was testing.
I will try again.

**Comment by ghost** [comment]
It would be better to replace PWM_RESOLUTION and PWM_MAX_DUTY_CYCLE with variables like _writeResolution to set them directly inside analogWriteResolution().
I will add the modification when the F1 will be merged inside the generic repository.

**Comment by Adminius** [comment]
This ticket will be reopened in general repository .
