### ISSUE TITLE
HSE Prediv Value configuration is missing in initialization

### ISSUE THREAD

**Issue by danieleff** [stm32duino/Arduino_Core_STM32F1#6]
Inside libstm32f103c hw_config.c SystemClock_Config() the HSEPredivValue is not initialized:
`RCC_OscInitStruct.HSEPredivValue = RCC_HSE_PREDIV_DIV1`;

**Comment by rogerclarkmelbourne** [comment]
Thanks. 
I will see if Wi6Labs are willing to confirm this and fix, or whether i need to do it ;-)

**Comment by rogerclarkmelbourne** [comment]
Looks like you fixed it, the code now has

`RCC_OscInitStruct.HSEPredivValue = RCC_HSE_PREDIV_DIV1;`
